    <news-item 
        title="{{ $news->title }}" 
        news-id="{{ $news->id }}"
        user-id="{{ $news->author->id }}" 
        structure-id="{{ $news->structure->id }}" 
        user-name="{{ $news->author->firstname .' '. $news->author->lastname}}"
        structure-name="{{ $news->structure->name }}"
        text-content="{{ $news->content }}"
        can-delete="{{ Auth::user()->can('delete', $news) ? true : false }}"
        can-edit="{{ Auth::user()->can('update', $news) ? true : false }}" 
        update-route="{{ route('news.update', $news->id) }}"
        delete-route="{{ route('news.delete', $news->id) }}"
        user-route="{{ route('user.profile.show', $news->author->id) }}"
        structure-route="{{ route('structure.profile.show', $news->structure->id) }}"
    ></news-item>